run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - errcheck
    - goimports
    - gosimple
    - govet
    - misspell
    - staticcheck
    - structcheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosimple

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
