name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.x
      - name: Add $GOPATH/bin to $PATH
        run: echo "::add-path::$(go env GOPATH)/bin"
      - name: Test
        run: make test-cover
      - name: Lint
        run: make lint
      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-profile: c.out
          parallel: true
          job-number: ${{ strategy.job-index }}
  finish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: finish coverage report
        uses: shogo82148/actions-goveralls@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
